name: Release Docker Image

env:
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

  AWS_DEFAULT_REGION: us-east-1
  AWS_ECR_ARN: ${{secrets.AWS_ECR_ARN}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ECR_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ECR_ACCESS_KEY_SECRET}}

  DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}


on:
  push:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run test and Generate Coverage Report
        run: npm run coverage

      - name: Update SonarCloud Code Report
        run: npm run sonar

      - name: Extract project version
        run : |
          BUILD_NUMBER=$(node -p -e "require('./package.json').version")
          echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV 
          echo "Extracted Build Number: ${BUILD_NUMBER}"

      - name: Build angular project
        run: npm run build -- --configuration=production

      - name: Build Docker Image
        run: |
          docker build -t flight-tracker-frontend:latest .

      - name: Authenticate to dockerhub
        run : |
          docker login -u ewagner2802 --password $DOCKERHUB_ACCESS_TOKEN

      - name: Build and Publish Docker Image to dockerhub
        run : |
          docker tag flight-tracker-frontend:latest ewagner2802/flighttrackerfrontend:${BUILD_NUMBER}
          docker tag flight-tracker-frontend:latest ewagner2802/flighttrackerfrontend:latest

          docker push ewagner2802/flighttrackerfrontend --all-tags